# Generated by Django 4.1.6 on 2023-02-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_rename_super_type_super_super_types'),
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperType',
            new_name='SuperTypes',
        ),
    ]
