# Generated by Django 4.1.6 on 2023-02-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperType',
        ),
    ]
