# Generated by Django 4.1.6 on 2023-02-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_super_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='super_types',
        ),
    ]
